import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { LocalFont } from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

const poppins = LocalFont({
  src: [
    {
      path: "../../public/fonts/Poppins-Regular.ttf",
      format: "400",
    },
    {
      path: "../../public/fonts/Poppins-Medium.ttf",
      format: "500",
    },
    {
      path: "../../public/fonts/Poppins-Bold.ttf",
      format: "700",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
